name: musicbrainz_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/weakteam/musicbrainz-dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  http: ^0.12.0+4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
